name: GitHub Pages

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: npm install && npm run dist
        
      - name: Get targets for 3.x.x-maintenance
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
            cd dist
            curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o firmware.zip "https://api.github.com/repos/ExpressLRS/ExpressLRS/actions/artifacts/$ARTIFACT_ID/zip"
            unzip firmware.zip
            rm firmware.zip
            mv firmware 3.x.x-maintenance
            mkdir firmware
            mv 3.x.x-maintenance firmware/
        env:
          ARTIFACT_ID: "309207520"
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          
